CREATE TABLE IF NOT EXISTS downloads ( 
    id INT NOT NULL AUTO_INCREMENT, 
    name VARCHAR(255) NULL DEFAULT NULL,     
    url VARCHAR(255) NULL DEFAULT NULL, 
    status TINYINT(1) NOT NULL DEFAULT 0,
    size INT NOT NULL DEFAULT 0,
    creaetd_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (id) 
);